G3_TRIG:          1
G3_SWIT:          [4, 100]
G3_DEBU:          [0, 0, 1]
G3_RAYL:          1
G3_STRA:          1
G3_AUTO:          0        #Select automatic STMIN etc... calc. (AUTO 1) or manual (AUTO 0)
G3_ABAN:          0        #Restore 3.16 behaviour for abandoned tracks
G3_OPTI:          2        #Select optimisation level for GEANT geometry searches (0,1,2)
G3_ERAN:          5.e-7
G3_CKOV:          1        #Cerenkov photons

MonteCarlo_Process:
    PAIR:         1        #pair production
    COMP:         1        #Compton scattering
    PHOT:         1        #photo electric effect
    PFIS:         0        #photofission
    DRAY:         1        #delta-ray
    ANNI:         1        #annihilation
    BREM:         1        #bremsstrahlung
    HADR:         1        #hadronic process
    MUNU:         1        #muon nuclear interaction
    DCAY:         1        #decay
    LOSS:         1        #energy loss
    MULS:         0        #multiple scattering

MonteCarlo_Cut:
    CUTGAM:       1.0E-3   #gammas (GeV)
    CUTELE:       1.0E-3   #electrons (GeV)
    CUTNEU:       1.0E-3   #neutral hadrons (GeV)
    CUTHAD:       1.0E-3   #charged hadrons (GeV)
    CUTMUO:       1.0E-3   #muons (GeV)
    BCUTE:        1.0E-3   #electron bremsstrahlung (GeV)
    BCUTM:        1.0E-3   #muon and hadron bremsstrahlung (GeV)
    DCUTE:        1.0E-3   #delta-rays by electrons (GeV)
    DCUTM:        1.0E-3   #delta-rays by muons (GeV)
    PPCUTM:       1.0E-3   #direct pair production by muons (GeV)
    TOFMAX:       1.E10    #time of flight cut in seconds

FairStack_StoreSecondaries: true
FairStack_MinPoints:        0
